# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 12:49
from __future__ import unicode_literals

import anylink.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anylink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', anylink.fields.AnyLinkField(on_delete=django.db.models.deletion.PROTECT, to='anylink.AnyLink', verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='LinkableObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Linklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='linklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_project.Linklist'),
        ),
    ]
